/*
 Rocrail - Model Railroad Software

Copyright (c) 2002-2015 Robert Jan Versluis, Rocrail.net

 


 All rights reserved.
*/

#ifndef __channeltunedlg__
#define __channeltunedlg__

/**
@file
Subclass of ChannelTuneDlgGen, which is generated by wxFormBuilder.
*/

#include "channeltunegen.h"
#include "decoderbase.h"

//// end generated include

/** Implementing ChannelTuneDlgGen */
class ChannelTuneDlg : public ChannelTuneDlgGen
{
  DecoderBase* m_DecoderBase;
  int m_Channel;
  int m_Type;
  void initLabels();

	protected:
		// Handlers for ChannelTuneDlgGen events.
		void onMaxRange( wxSpinEvent& event );
		void onMinRange( wxSpinEvent& event );
		void onPreset( wxCommandEvent& event );
		void onOffPos( wxScrollEvent& event );
		void onOffPosRelease( wxScrollEvent& event );
		void onOnPos( wxScrollEvent& event );
		void onOnPosRelease( wxScrollEvent& event );
		void onOK( wxCommandEvent& event );
		void onHelp( wxCommandEvent& event );
	public:
		/** Constructor */
		ChannelTuneDlg( wxWindow* parent, DecoderBase* decoderbase, int channel, int type, int offpos, int onpos, bool servo );
	//// end generated class members
		int getOffPos();
    int getOnPos();
	
};

#endif // __channeltunedlg__
