/*
 Rocrail - Model Railroad Software

Copyright (c) 2002-2015 Robert Jan Versluis, Rocrail.net

 


 All rights reserved.
*/
#ifndef __dtopswdlg__
#define __dtopswdlg__

/**
@file
Subclass of dtopswdlg, which is generated by wxFormBuilder.
*/

#include "dtopswdlggen.h"
#include "wx/timer.h"

#include "rocs/public/node.h"
#include "rocs/public/queue.h"

#define DTOPSW_Timer 10199

/** Implementing dtopswdlg */
class DTOpSwDlg : public dtopswdlg
{
  void initLabels();
  void initValues();
  void onTimer(wxTimerEvent& event);
  void sendPacket();

  iOQueue m_Queue;
  iONode m_SendedCmd;
  wxTimer* m_Timer;
  int m_iOpSw[256];

  void evaluateEvent( int val );
  void onBoardType( wxCommandEvent& event );
  void onReadAll( wxCommandEvent& event );
  void onWriteAll( wxCommandEvent& event );
  void onOK( wxCommandEvent& event );
  void onHelp( wxCommandEvent& event );

public:
  /** Constructor */
  DTOpSwDlg( wxWindow* parent );
  void event( iONode event );
};

#endif // __dtopswdlg__
