/*
 Rocrail - Model Railroad Software

Copyright (c) 2002-2015 Robert Jan Versluis, Rocrail.net

 All rights reserved.
*/

#ifndef __hueconfdlg__
#define __hueconfdlg__

/**
@file
Subclass of HueConfDlgGen, which is generated by wxFormBuilder.
*/

#include "hueconfdlggen.h"

#include "rocs/public/node.h"


/** Implementing HueConfDlgGen */
class HueConfDlg : public HueConfDlgGen
{
  int m_Col;
  int m_Row;
  void initLabels();

	protected:
		// Handlers for HueConfDlgGen events.
		void onGetLights( wxCommandEvent& event );
		void onFindLights( wxCommandEvent& event );
		void onHelp( wxCommandEvent& event );
		void onOK( wxCommandEvent& event );
		void onClose( wxCloseEvent& event );
		void onLightCellChange( wxGridEvent& event );
		void onLightSet( wxCommandEvent& event );
		void onLightCellDClick( wxGridEvent& event );
    void onBridgeNameSet( wxCommandEvent& event );
    void onBridgeGet( wxCommandEvent& event );
    void onSetBridgeUserName( wxCommandEvent& event );
    void onLightOn( wxCommandEvent& event );
    void onLightOff( wxCommandEvent& event );
    void onLightCellSelect( wxGridEvent& event );
    void onBrightness( wxScrollEvent& event );
    void onBrightnessThumbRelease( wxScrollEvent& event );

	public:
		/** Constructor */
		HueConfDlg( wxWindow* parent );
	  void event(iONode node);
	
};

#endif // __hueconfdlg__
