/*
 Rocrail - Model Railroad Software

 Copyright (C) 2002-2015 Rob Versluis, Rocrail.net

 This program is free software; you can redistribute it and/or
 modify it under the terms of the GNU General Public License
 as published by the Free Software Foundation; either version 3
 of the License, or (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/

#ifndef __hueconfdlg__
#define __hueconfdlg__

/**
@file
Subclass of HueConfDlgGen, which is generated by wxFormBuilder.
*/

#include "hueconfdlggen.h"

#include "rocs/public/node.h"


/** Implementing HueConfDlgGen */
class HueConfDlg : public HueConfDlgGen
{
  int m_Col;
  int m_Row;
  void initLabels();

	protected:
		// Handlers for HueConfDlgGen events.
		void onGetLights( wxCommandEvent& event );
		void onFindLights( wxCommandEvent& event );
		void onHelp( wxCommandEvent& event );
		void onOK( wxCommandEvent& event );
		void onClose( wxCloseEvent& event );
		void onLightCellChange( wxGridEvent& event );
		void onLightSet( wxCommandEvent& event );
		void onLightCellDClick( wxGridEvent& event );
    void onBridgeNameSet( wxCommandEvent& event );
    void onBridgeGet( wxCommandEvent& event );
    void onSetBridgeUserName( wxCommandEvent& event );
    void onLightOn( wxCommandEvent& event );
    void onLightOff( wxCommandEvent& event );
    void onLightCellSelect( wxGridEvent& event );
    void onBrightness( wxScrollEvent& event );
    void onBrightnessThumbRelease( wxScrollEvent& event );

	public:
		/** Constructor */
		HueConfDlg( wxWindow* parent );
	  void event(iONode node);
	
};

#endif // __hueconfdlg__
