/*
 Rocrail - Model Railroad Software

Copyright (c) 2002-2015 Robert Jan Versluis, Rocrail.net

 


 All rights reserved.
*/
#ifndef __mgv141dlg__
#define __mgv141dlg__

/**
@file
Subclass of mgv141gen, which is generated by wxFormBuilder.
*/

#include "mgv141dlggen.h"
#include "wx/timer.h"

#include "rocs/public/node.h"
#include "rocs/public/queue.h"

/** Implementing mgv141gen */
class MGV141Dlg : public mgv141gen
{
  void sendPacket();
  void makePacket( int offset, int port, int val1, bool sv_set, bool sendnow );
  void OnTimer(wxTimerEvent& event);
  void queryAddresses();
  void evaluateEvent( int type, int low, int sub, int sv, int val, int ver );

  int m_iLowAddress;
  int m_iSubAddress;
  iOQueue m_Queue;
  iONode m_SendedCmd;
  wxTimer* m_Timer;
  int m_TabAlign;
  int m_SV[256];


protected:
	// Handlers for mgv141gen events.
  void onUnitSelected( wxCommandEvent& event );
  void onQuery( wxCommandEvent& event );
	void onUnitSet( wxCommandEvent& event );
	void onWriteAll( wxCommandEvent& event );
	void onReadAll( wxCommandEvent& event );
	void onOK( wxCommandEvent& event );
	void onHelp( wxCommandEvent& event );
  void initLabels();

public:
	/** Constructor */
	MGV141Dlg( wxWindow* parent );
	void event( iONode event );
};

#endif // __mgv141dlg__
