/*
 Rocrail - Model Railroad Software

Copyright (c) 2002-2015 Robert Jan Versluis, Rocrail.net

 


 All rights reserved.
*/
#ifndef __mgvdlg__
#define __mgvdlg__


/**
@file
Subclass of mgvdlggen, which is generated by wxFormBuilder.
*/
#include "mgvdlggen.h"

#include "rocs/public/map.h"
#include "rocs/public/node.h"

/** Implementing phgdlggen */
class MGVDlg : public mgvdlggen
{
  bool m_bProgrammingMode;
  void initLabels();
  void initValues();
  void evaluate();
  void enableSetup(bool enable);
  void SetBit(int addr, int port, bool on);
  void SendNibble(int value);
  void EnterProgrammingMode();
  void ExitProgrammingMode();
  void OnServoSelect();

  iOMap m_MGVmap;
  iONode m_MGVServo;

public:
  /** Constructor */
  MGVDlg( wxWindow* parent );

  void OnProgrammingOn( wxCommandEvent& event );
  void OnProgrammingOff( wxCommandEvent& event );
  void OnServoSelect( wxCommandEvent& event );
  void OnServoLeftAngle( wxScrollEvent& event );
  void OnServoRightAngle( wxScrollEvent& event );
  void OnServoSpeed( wxScrollEvent& event );
  void OnServoRelay( wxCommandEvent& event );
  void OnOK( wxCommandEvent& event );
  void onHelp( wxCommandEvent& event );
  void OnResetBits( wxCommandEvent& event );
  void onSetLeftAngle( wxCommandEvent& event );
  void onSetRightAngle( wxCommandEvent& event );
  void onSetSpeed( wxCommandEvent& event );
  void setServoLeftAngle();
  void setServoRightAngle();
  void setServoSpeed();
  void setServoBounce();
  void OnServoBounce( wxScrollEvent& event );
  void onSetBounce( wxCommandEvent& event );

};

#endif /* __mgvdlg__ */
