/*
 Rocrail - Model Railroad Software

Copyright (c) 2002-2015 Robert Jan Versluis, Rocrail.net

 


 All rights reserved.
*/

#ifndef __bidibdlg__
#define __bidibdlg__

/**
@file
Subclass of bidibdlggen, which is generated by wxFormBuilder.
*/

#include "bidibdlggen.h"

#include "rocs/public/node.h"

/** Implementing bidibdlggen */
class BidibDlg : public bidibdlggen
{
protected:
	// Handlers for bidibdlggen events.
	void OnNodeList( wxCommandEvent& event );
	void OnCancel( wxCommandEvent& event );
	void OnOK( wxCommandEvent& event );
  void onConfigureNodes( wxCommandEvent& event );
  void onSubLib( wxCommandEvent& event );
  void OnHelp( wxCommandEvent& event );

  void initLabels();
  void initValues();
  void initNodes();
  void evaluate();
  void subLib();
  iONode m_Props;
  const char* m_Devices;


public:
	/** Constructor */
	BidibDlg( wxWindow* parent, iONode props, const char* devices=NULL );

};

#endif // __bidibdlg__
