/*
 Rocrail - Model Railroad Software

Copyright (c) 2002-2015 Robert Jan Versluis, Rocrail.net

 


 All rights reserved.
*/

#ifndef __cbusdlg__
#define __cbusdlg__

/**
@file
Subclass of cbusdlggen, which is generated by wxFormBuilder.
*/

#include "cbusdlggen.h"

#include "rocs/public/node.h"

/** Implementing cbusdlggen */
class CbusDlg : public cbusdlggen
{
protected:
  // Handlers for cbusdlggen events.
  void OnSublib( wxCommandEvent& event );
  void OnCancel( wxCommandEvent& event );
  void OnOK( wxCommandEvent& event );
  void OnHelp( wxCommandEvent& event );

  void initLabels();
  void initValues();
  void evaluate();
  iONode m_Props;
  const char* m_Devices;

public:
  /** Constructor */
  CbusDlg( wxWindow* parent, iONode props, const char* devices=NULL );
};

#endif // __cbusdlg__
