/*
 Rocrail - Model Railroad Software

Copyright (c) 2002-2015 Robert Jan Versluis, Rocrail.net

 


 All rights reserved.
*/

#ifndef __dcc232dlg__
#define __dcc232dlg__

/**
@file
Subclass of dcc232gen, which is generated by wxFormBuilder.
*/

#include "dcc232dlggen.h"

#include "rocs/public/node.h"

/** Implementing dcc232gen */
class DCC232Dlg : public dcc232gen
{
  void initLabels();
  void initValues();
  void evaluate();
  void onOK( wxCommandEvent& event );
  void onCancel( wxCommandEvent& event );
  void onHelp( wxCommandEvent& event );
  iONode m_Props;
  const char* m_Devices;

public:
	/** Constructor */
	DCC232Dlg( wxWindow* parent, iONode props, const char* devices=NULL );
};

#endif // __dcc232dlg__
