/*
 Rocrail - Model Railroad Software

Copyright (c) 2002-2015 Robert Jan Versluis, Rocrail.net

 All rights reserved.
*/

#ifndef __dmxdlg__
#define __dmxdlg__

/**
@file
Subclass of dmxdlggen, which is generated by wxFormBuilder.
*/

#include "dmxdlggen.h"
#include "rocs/public/node.h"

//// end generated include

/** Implementing dmxdlggen */
class DmxDlg : public dmxdlggen
{
  iONode m_Props;
  void initLabels();
  void initValues();
  bool evaluate();
	protected:
		// Handlers for dmxdlggen events.
		void onCancel( wxCommandEvent& event );
		void onHelp( wxCommandEvent& event );
		void onOK( wxCommandEvent& event );
	public:
		/** Constructor */
		DmxDlg( wxWindow* parent, iONode props );
	//// end generated class members
	
};

#endif // __dmxdlg__
