/*
 Rocrail - Model Railroad Software

Copyright (c) 2002-2015 Robert Jan Versluis, Rocrail.net

 


 All rights reserved.
*/

#ifndef __rocnetdlg__
#define __rocnetdlg__

/**
@file
Subclass of rocnetdlggen, which is generated by wxFormBuilder.
*/

#include "rocnetdlggen.h"
#include "rocs/public/node.h"

/** Implementing rocnetdlggen */
class RocNetDlg : public rocnetdlggen
{
protected:
	// Handlers for rocnetdlggen events.
	void OnSublib( wxCommandEvent& event );
	void OnCancel( wxCommandEvent& event );
	void OnOK( wxCommandEvent& event );
	void OnHelp( wxCommandEvent& event );
	void onNodeListSelected( wxListEvent& event );
	
  void initLabels();
  void initValues();
  void initNodeList();
  void evaluate();
  iONode m_Props;
  const char* m_Devices;

public:
	/** Constructor */
	RocNetDlg( wxWindow* parent, iONode props, const char* devices=NULL );
};

#endif // __rocnetdlg__
