/*
 Rocrail - Model Railroad Software
 Copyright (c) 2002-2015 Robert Jan Versluis, Rocrail.net
 All rights reserved.
*/

#ifndef __aboxdlg__
#define __aboxdlg__

/**
@file
Subclass of AboxDlgGen, which is generated by wxFormBuilder.
*/

#include "aboxdlggen.h"

#include "rocs/public/node.h"
#include "rocs/public/list.h"

//// end generated include

/** Implementing AboxDlgGen */
class ABoxDlg : public AboxDlgGen
{
	protected:
		// Handlers for AboxDlgGen events.
		void onFind( wxCommandEvent& event );
		void onAdd( wxCommandEvent& event );
		void onSelectFile( wxCommandEvent& event );
    void onStubActivated( wxListEvent& event );
    void onStubSelected( wxListEvent& event );
    void onHelp( wxCommandEvent& event );
    void onOK( wxCommandEvent& event );
    void onOpen( wxCommandEvent& event );
    void onDelete( wxCommandEvent& event );
	public:
		/** Constructor */
		ABoxDlg( wxWindow* parent );
    ~ABoxDlg();
	//// end generated class members
    void event(iONode node);
	private:
    void initLabels();
    void clearStubList();
    void openStub();
    iOList m_StubList;
    int m_SelectedStub;

};

#endif // __aboxdlg__
