/*
 Rocrail - Model Railroad Software
 Copyright (c) 2002-2015 Robert Jan Versluis, Rocrail.net
 All rights reserved.
*/

#ifndef __aboxdlg__
#define __aboxdlg__

/**
@file
Subclass of AboxDlgGen, which is generated by wxFormBuilder.
*/

#include "aboxdlggen.h"

#include "rocs/public/node.h"
#include "rocs/public/list.h"


#define DATABLOCK 32*1024

/** Implementing AboxDlgGen */
class ABoxDlg : public AboxDlgGen
{
	protected:
		// Handlers for AboxDlgGen events.
		void onFind( wxCommandEvent& event );
		void onAdd( wxCommandEvent& event );
		void onSelectFile( wxCommandEvent& event );
    void onStubActivated( wxListEvent& event );
    void onStubSelected( wxListEvent& event );
    void onHelp( wxCommandEvent& event );
    void onOK( wxCommandEvent& event );
    void onOpen( wxCommandEvent& event );
    void onDelete( wxCommandEvent& event );
    void onModify( wxCommandEvent& event );
    void onStubCol( wxListEvent& event );
    void onFindTextEnter( wxCommandEvent& event );
    void onShowPath( wxCommandEvent& event );
	public:
		/** Constructor */
		ABoxDlg( wxWindow* parent, const char* text=NULL );
    ~ABoxDlg();
	//// end generated class members
    void event(iONode node);
	private:
    void initLabels();
    void initResult();
    void clearStubList();
    void openStub();
    void showStub();
    void doFind(const char* text);
    bool readDataBlock(const char* filename, iONode node, int nr);
    void executeStub(const char* filepath);
    iOList m_StubList;
    int m_SelectedStub;
    bool m_ReadOnly;
    int m_SortCol;
    iONode m_Ini;
    char m_AddedFilename[1024];
    char m_AddedUID[128];
    int m_AddedPart;
    char m_DownloadFilename[1024];
    char m_DownloadUID[128];
    int m_DownloadPart;

};

#endif // __aboxdlg__
