/*
 Rocrail - Model Railroad Software

Copyright (c) 2002-2015 Robert Jan Versluis, Rocrail.net

 


 All rights reserved.
*/
#ifndef __accdecdlg__
#define __accdecdlg__

/**
@file
Subclass of Accessory Decoders, which is generated by wxFormBuilder.
*/

#include "accdecgendlg.h"
#include "basedlg.h"

#include "rocs/public/node.h"


//// end generated include

/** Implementing Accessory Decoders */
class AccDecDlg : public AccDecGenDlg, public BaseDialog
{
  iONode m_Props;
  void initCVDesc();
  const char* m_CVDesc[256];
  int m_iSelectedCV;
  iONode m_CVNodes[1024];

protected:
		// Handlers for Accessory Decoders events.
		void onAdd( wxCommandEvent& event );
		void onDelete( wxCommandEvent& event );
		void onCancel( wxCommandEvent& event );
		void onOK( wxCommandEvent& event );
		void onApply( wxCommandEvent& event );
		void onSelected( wxListEvent& event );
		void onImage( wxCommandEvent& event );
		void onDoc( wxCommandEvent& event );
		void onColClick( wxListEvent& event );
    void onCVCell( wxGridEvent& event );
    void onCVModify( wxCommandEvent& event );
    void onHelp( wxCommandEvent& event );
    void onUsageListActivated( wxListEvent& event );
    void onUsageListSelected( wxListEvent& event );
    void onOpenDoc( wxCommandEvent& event );
    void aboxID( wxMouseEvent& event );
    void aboxManu( wxMouseEvent& event );
    void aboxCatNr( wxMouseEvent& event );

		void initLabels();
		bool initIndex();
    void initUsage();
		void initValues();
		bool evaluate();
	public:
		/** Constructor */
		AccDecDlg( wxWindow* parent );
	//// end generated class members
	
};

#endif // __accdecdlg__
