/*
 Rocrail - Model Railroad Software

Copyright (c) 2002-2015 Robert Jan Versluis, Rocrail.net

 


 All rights reserved.
*/
#ifndef __cmdrecorder__
#define __cmdrecorder__

/**
@file
Subclass of CmdRecorderGen, which is generated by wxFormBuilder.
*/
#include "wx/timer.h"

#include "cmdrecordergen.h"

//// end generated include

/** Implementing CmdRecorderGen */
class CmdRecorder : public CmdRecorderGen
{
  void initList();
  void initLabels();
  CmdRecorder** m_Me;
  wxTimer* m_Timer;

	protected:
		// Handlers for CmdRecorderGen events.
		void onRecord( wxCommandEvent& event );
		void onStop( wxCommandEvent& event );
		void onPause( wxCommandEvent& event );
		void onPlay( wxCommandEvent& event );
		void onCmdSelected( wxCommandEvent& event );
		void onModify( wxCommandEvent& event );
		void onImport( wxCommandEvent& event );
    void onExport( wxCommandEvent& event );
		void onDelete( wxCommandEvent& event );
    void onInsert( wxCommandEvent& event );
		void onOK( wxCommandEvent& event );
    void onClose( wxCloseEvent& event );
    void onClear( wxCommandEvent& event );
    void onHelp( wxCommandEvent& event );
    void onCreateRoute( wxCommandEvent& event );
	public:
		/** Constructor */
		CmdRecorder( wxWindow* parent );
		void SetMe( CmdRecorder** me) {m_Me=me;}
	  void OnTimer(wxTimerEvent& event);

	//// end generated class members
	
};

#endif // __cmdrecorder__
