/*
 Rocrail - Model Railroad Software

Copyright (c) 2002-2015 Robert Jan Versluis, Rocrail.net

 


 All rights reserved.
*/

#ifndef __donkey__
#define __donkey__

/**
@file
Subclass of DonKeyGen, which is generated by wxFormBuilder.
*/

#include "donkeygen.h"

#include "rocs/public/node.h"

/** Implementing DonKeyGen */
class DonKey : public DonKeyGen
{
protected:
	// Handlers for DonKeyGen events.
	void OnSplash( wxMouseEvent& event );
	void OnLoadKey( wxCommandEvent& event );
	void OnDonateNow( wxCommandEvent& event );
  void OnOK( wxCommandEvent& event );
  void onHelp( wxCommandEvent& event );
	
public:
	/** Constructor */
	DonKey( wxWindow* parent, iONode ini );

private:
  void initLabels();
  void initValues();
  iONode m_Ini;	
};

#endif // __donkey__
