/*
 Rocrail - Model Railroad Software

Copyright (c) 2002-2015 Robert Jan Versluis, Rocrail.net

 


 All rights reserved.
*/
#ifndef __gotodlg__
#define __gotodlg__

/**
@file
Subclass of gotodlggen, which is generated by wxFormBuilder.
*/

#include "gotodlggen.h"

//// end generated include

#include "basedlg.h"

#include "rocs/public/node.h"

/** Implementing gotodlggen */
class GotoDlg : public gotodlggen, public BaseDialog
{
  void initIndex();
  iONode m_Props;
  const char* m_LocoID;

	protected:
		// Handlers for gotodlggen events.
		void onColClick( wxListEvent& event );
		void onSelected( wxListEvent& event );
		void onBlocks( wxCommandEvent& event );
		void onStages( wxCommandEvent& event );
		void onFYs( wxCommandEvent& event );
		void onTTs( wxCommandEvent& event );
		void onCancel( wxCommandEvent& event );
		void onOK( wxCommandEvent& event );
    void onAdd2Trip( wxCommandEvent& event );
    void onHelp( wxCommandEvent& event );
	public:
		/** Constructor */
    GotoDlg( wxWindow* parent, const char* lcid );
	//// end generated class members
		iONode getSelected() {return m_Props;}
	
};

#endif // __gotodlg__
