/*
 Rocrail - Model Railroad Software

Copyright (c) 2002-2015 Robert Jan Versluis, Rocrail.net

 


 All rights reserved.
*/

#ifndef __powerctrldlg__
#define __powerctrldlg__

/**
@file
Subclass of powerctrlgen, which is generated by wxFormBuilder.
*/

#include "powerctrlgen.h"

#include "rocs/public/node.h"
#include "rocs/public/map.h"

/** Implementing powerctrlgen */
class PowerCtrlDlg : public powerctrlgen
{
  void initLabels();
  void initValues(iONode event);
  iONode m_SelBooster;
  iOMap m_BoosterMap;
  int m_SelectedRow;
  int m_SortColumn;

  void paintHistory();
  void addRow(iONode booster);


protected:
	// Handlers for powerctrlgen events.
	void OnOn( wxCommandEvent& event );
	void OnOff( wxCommandEvent& event );
	void OnOK( wxCommandEvent& event );
  void onCellLeftClick( wxGridEvent& event );
  void onCellRightClick( wxGridEvent& event );
  void onSize( wxSizeEvent& event );
  void onClose( wxCloseEvent& event );
  void onResetStat( wxCommandEvent& event );
  void OnHelp( wxCommandEvent& event );
  void onLabelLeftClick( wxGridEvent& event );

public:
	/** Constructor */
	PowerCtrlDlg( wxWindow* parent );
  void powerEvent(iONode event);
};

#endif // __powerctrldlg__
