/*
 Rocrail - Model Railroad Software

Copyright (c) 2002-2015 Robert Jan Versluis, Rocrail.net

 


 All rights reserved.
*/

#ifndef __powermandlg__
#define __powermandlg__

/**
@file
Subclass of powermandlggen, which is generated by wxFormBuilder.
*/
#include "powermandlggen.h"
#include "basenotebook.h"

#include "rocs/public/node.h"

/** Implementing powermandlggen */
class PowerManDlg : public powermandlggen
{
  void initLabels();
  void initIndex();
  void initValues();
  bool evaluate();

  int m_TabAlign;
  int m_SetPage;
  iONode m_Props;
  int m_SortCol;

protected:
	// Handlers for powermandlggen events.
	void OnAddBooster( wxCommandEvent& event );
	void OnDelBooster( wxCommandEvent& event );
	void OnAddModule( wxCommandEvent& event );
	void OnDelModule( wxCommandEvent& event );
	void OnAddBlock( wxCommandEvent& event );
	void OnDelBlock( wxCommandEvent& event );
	void OnApply( wxCommandEvent& event );
	void OnCancel( wxCommandEvent& event );
	void OnOK( wxCommandEvent& event );
  void onSetPage( wxCommandEvent& event );
  void onBoosterListColumn( wxListEvent& event );
  void onBoosterSelect( wxListEvent& event );
  void onBlockSelect( wxCommandEvent& event );
  void onModuleSelect( wxCommandEvent& event );
  void onActions( wxCommandEvent& event );
  void OnHelp( wxCommandEvent& event );
  void setSelection(const char* ID);
  int findID( const char* ID );


public:
	/** Constructor */
	PowerManDlg( wxWindow* parent );
};

#endif // __powermandlg__
