/*
 Rocrail - Model Railroad Software

Copyright (c) 2002-2015 Robert Jan Versluis, Rocrail.net

 


 All rights reserved.
*/
#ifndef __stagedlg__
#define __stagedlg__

/**
@file
Subclass of stagedlggen, which is generated by wxFormBuilder.
*/

#include "stagedlggen.h"
#include "basedlg.h"

#include "rocs/public/node.h"

/** Implementing stagedlggen */
class StageDlg : public stagedlggen, public BaseDialog
{
  iONode m_Props;
  iONode m_Section;
  int    m_TabAlign;
  int    m_SetPage;
  int    m_SortCol;

  void initLabels();
  bool evaluate();
  void initSections();
  void initValues();
  void initIndex();
  int findID( const char* ID );
  void setSelection(const char* ID);
  int getLength(iONode stage, int* nrsection);


protected:
	// Handlers for stagedlggen events.
	void OnSectionList( wxCommandEvent& event );
	void OnSectionAdd( wxCommandEvent& event );
	void OnSectionModify( wxCommandEvent& event );
	void OnSectionDelete( wxCommandEvent& event );
  void OnCancel( wxCommandEvent& event );
  void OnOK( wxCommandEvent& event );
  void OnSetPage(wxCommandEvent& event);
  void OnFreeSection( wxCommandEvent& event );
  void OnSetLoco( wxCommandEvent& event );
  void OnFreeAll( wxCommandEvent& event );
  void onActions( wxCommandEvent& event );
  void onStageColumn( wxListEvent& event );
  void onStageList( wxListEvent& event );
  void onIndexNew( wxCommandEvent& event );
  void onIndexDelete( wxCommandEvent& event );
  void OnApply( wxCommandEvent& event );
  void OnHelp( wxCommandEvent& event );
  void onDoc( wxCommandEvent& event );

public:
	/** Constructor */
	StageDlg( wxWindow* parent, iONode p_Props );
};

#endif // __stagedlg__
