/*
 Rocrail - Model Railroad Software

Copyright (c) 2002-2015 Robert Jan Versluis, Rocrail.net

 


 All rights reserved.
*/
#ifndef __throttledlg__
#define __throttledlg__

/**
@file
Subclass of ThrottleDlgGen, which is generated by wxFormBuilder.
*/

#include "throttledlggen.h"

//// end generated include
#include "rocs/public/node.h"
#include "rocs/public/list.h"
#include "rocs/public/map.h"

/** Implementing ThrottleDlgGen */
class ThrottleDlg : public ThrottleDlgGen
{
  iONode m_Props;
  int m_iFnGroup;
  bool m_bDir;
  bool m_bFn;
  bool m_bSecAddr;
  int m_iSpeed1;
  int m_iSpeed2;
  bool m_bFx[32];
  iOList m_DlgList;
  iOMap m_DlgMap;
  iONode getConsistLoco();

	public:
  /** Constructor */
  ThrottleDlg( wxWindow* parent, iOList list, iOMap map, const char* locid=NULL );
	//// end generated class members
  ~ThrottleDlg();
  void onButton(wxCommandEvent& event);
  void onSlider(wxScrollEvent& event);
  void onBinStateKey( wxKeyEvent& event );
  void onClose( wxCloseEvent& event );
  void onDestroy( wxWindowDestroyEvent& event );
  void modelEvent( iONode evt );

  void updateImage();
  void setFLabels(bool init);
  void setFLabels(iONode p_Props, bool merge, bool init, int fmap=0xFFFFFFFF);
  wxBitmap* getIcon(const char* icon);
  void funCmd(int fidx, bool on);
  void speedCmd(bool sendCmd);
  bool setFX( iONode node );

};

#endif // __throttledlg__
