/*
 Rocrail - Model Railroad Software

Copyright (c) 2002-2015 Robert Jan Versluis, Rocrail.net

 


 All rights reserved.
*/
#ifndef __toursdlg__
#define __toursdlg__

/**
@file
Subclass of toursdlggen, which is generated by wxFormBuilder.
*/

#include "toursdlggen.h"
#include "rocs/public/node.h"

/** Implementing toursdlggen */
class ToursDlg : public toursdlggen
{
  iONode m_Props;
  bool   m_bSave;
  const char* m_StartBlock;

  void initLabels();
  void initIndex();
  void initValues();
  void initScheduleCombo();
  bool evaluate();

public:
	/** Constructor */
	ToursDlg( wxWindow* parent );
  ToursDlg( wxWindow* parent, iONode tour, bool save, const char* startblock=NULL );
  iONode getProperties() { return m_Props; };

  void onAddTour( wxCommandEvent& event );
  void onModifyTour( wxCommandEvent& event );
  void onDeleteTour( wxCommandEvent& event );
  void onApply( wxCommandEvent& event );
  void onTourSelect( wxCommandEvent& event );
  void onEntryAdd( wxCommandEvent& event );
  void onEntryDelete( wxCommandEvent& event );
  void onCancel( wxCommandEvent& event );
  void onOK( wxCommandEvent& event );
  void onShowAll( wxCommandEvent& event );
  void onHelp( wxCommandEvent& event );
  void onScheduleProps( wxCommandEvent& event );
  void onUp( wxCommandEvent& event );
  void onDown( wxCommandEvent& event );
  void onCopy( wxCommandEvent& event );

  static bool isFirst(iONode tour, const char* startblock);

};

#endif // __toursdlg__
