/*
 Rocrail - Model Railroad Software

Copyright (c) 2002-2015 Robert Jan Versluis, Rocrail.net

 All rights reserved.
*/

#ifndef __tracedlg__
#define __tracedlg__

/**
@file
Subclass of TraceDlgGen, which is generated by wxFormBuilder.
*/

#include "tracedlggen.h"
#include "rocs/public/node.h"
#include "rocs/public/thread.h"

//// end generated include

/** Implementing TraceDlgGen */
class TraceDlg : public TraceDlgGen
{
  public:
    char* m_TraceFile;
    void initLabels();
    char* m_Text;
    iOThread m_FormatThread;
    int m_iLine;

	protected:
		// Handlers for TraceDlgGen events.
		void onOpen( wxCommandEvent& event );
		void onHelp( wxCommandEvent& event );
		void onOK( wxCommandEvent& event );
    void onObjectType( wxCommandEvent& event );
    void onSearch( wxCommandEvent& event );
    void onClose( wxCloseEvent& event );
    void addLine(const char* text);
    void onLevel( wxCommandEvent& event );
    void onServerTraces( wxCommandEvent& event );
    void onID( wxCommandEvent& event );
    void onText( wxCommandEvent& event );
    void doLine( wxCommandEvent& event );
    void onSave( wxCommandEvent& event );

	public:
		/** Constructor */
		TraceDlg( wxWindow* parent );
    ~TraceDlg();
    void traceEvent(iONode node);
	//// end generated class members
	
};

#endif // __tracedlg__
