/*
 Rocrail - Model Railroad Software

Copyright (c) 2002-2015 Robert Jan Versluis, Rocrail.net

 All rights reserved.
*/

#ifndef __trackpickerdlg__
#define __trackpickerdlg__

#include "rocview/symbols/renderer.h"
#include "rocs/public/list.h"

/**
@file
Subclass of TrackPickerDlgGen, which is generated by wxFormBuilder.
*/

#include "trackpickerdlggen.h"

//// end generated include

/** Implementing TrackPickerDlgGen */
class TrackPickerDlg : public TrackPickerDlgGen
{
  iOList m_SymbolList;

  SymbolRenderer* m_Renderer;
  void onTrackCellLeftClick( wxGridEvent& event );
  void onPageChanged( wxListbookEvent& event );
  void onHelp( wxCommandEvent& event );
  void initSymbols();
  void initGrid();

	public:
		/** Constructor */
		TrackPickerDlg( wxWindow* parent );
	  void onClose( wxCloseEvent& event );
	
};

#endif // __trackpickerdlg__
