/*
 Rocrail - Model Railroad Software

Copyright (c) 2002-2015 Robert Jan Versluis, Rocrail.net

 All rights reserved.
*/

#ifndef __variabledlg__
#define __variabledlg__

/**
@file
Subclass of VariableDlgGen, which is generated by wxFormBuilder.
*/

#include "variabledlggen.h"

//// end generated include
#include "basedlg.h"

#include "rocs/public/node.h"

/** Implementing VariableDlgGen */
class VariableDlg : public VariableDlgGen, public BaseDialog
{
	protected:
		// Handlers for VariableDlgGen events.
    void onClose( wxCloseEvent& event );
		void onNew( wxCommandEvent& event );
		void onDelete( wxCommandEvent& event );
		void onApply( wxCommandEvent& event );
		void onCancel( wxCommandEvent& event );
		void onHelp( wxCommandEvent& event );
		void onOK( wxCommandEvent& event );
		void onListSelected( wxListEvent& event );
		void onActions( wxCommandEvent& event );
		void onListCol( wxListEvent& event );
		void onDoc( wxCommandEvent& event );

		void initIndex();
    void initLabels();
    void initValues();
    bool evaluate();
    void setSelection(const char* ID);
    int findID( const char* ID );

    iONode m_Props;
    int m_SortCol;
	public:
		/** Constructor */
		VariableDlg( wxWindow* parent );
	//// end generated class members
	
};

#endif // __variabledlg__
