/*
 Rocrail - Model Railroad Software

Copyright (c) 2002-2015 Robert Jan Versluis, Rocrail.net

 All rights reserved.
*/
#ifndef __weatherdlg__
#define __weatherdlg__

/**
@file
Subclass of WeatherDlgGen, which is generated by wxFormBuilder.
*/

#include "weatherdlggen.h"

//// end generated include
#include "rocs/public/node.h"
#include "rocview/public/listener.h"

/** Implementing WeatherDlgGen */
class WeatherDlg : public WeatherDlgGen, public Listener
{
  iONode m_PropsList;
  iONode m_Props;
  int m_SelectedRow;
  void initLabels();
  void initIndex();
  void initValues();
  void initThemeValues();
  void initThemeIndex();
  bool evaluate();
  bool evaluateTheme();
  void initColorGrid();
  void ShowCol(int col);
  void HideCol(int col);
	protected:
		// Handlers for WeatherDlgGen events.
		void onCancel( wxCommandEvent& event );
		void onOK( wxCommandEvent& event );
		void onApply( wxCommandEvent& event );
		void onActivateWeather( wxCommandEvent& event );
    void onDeactivateWeather( wxCommandEvent& event );
		void onHelp( wxCommandEvent& event );
    void onThemeSelected( wxCommandEvent& event );
    void onThemeAdd( wxCommandEvent& event );
    void onThemeModify( wxCommandEvent& event );
    void onThemeDelete( wxCommandEvent& event );
    void onIndexList( wxCommandEvent& event );
    void onAddWeather( wxCommandEvent& event );
    void onDeleteWeather( wxCommandEvent& event );
    void onActions( wxCommandEvent& event );
    void onColorCellChanged( wxGridEvent& event );
    void onColorCellSelect( wxGridEvent& event );
    void onColorLabelClick( wxGridEvent& event );
    void onColorImport( wxCommandEvent& event );
    void onColorExport( wxCommandEvent& event );
    void onColorCellLeftDClick( wxGridEvent& event );
    void onColorLabelDClick( wxGridEvent& event );
    void onColorWhite( wxCommandEvent& event );
    void onColorWhite2( wxCommandEvent& event );
    void onColorBrightness( wxCommandEvent& event );
    void onColorSaturation( wxCommandEvent& event );
    void onColorPickerWhite1( wxColourPickerEvent& event );
    void onColorPickerWhite2( wxColourPickerEvent& event );
    void onColorPickerBrightness( wxColourPickerEvent& event );
    void onColorPickerSaturation( wxColourPickerEvent& event );

	public:
		/** Constructor */
		WeatherDlg( wxWindow* parent, iONode props );
		void handleEvent( iONode node );
	//// end generated class members
	
};

#endif // __weatherdlg__
