/*
 Rocrail - Model Railroad Software
 Copyright (c) 2002-2015 Robert Jan Versluis, Rocrail.net
 All rights reserved.
*/

#ifndef __widgetspanel__
#define __widgetspanel__

/**
@file
Subclass of WidgetsPanel, which is generated by wxFormBuilder.
*/

#include <wx/sizer.h>
#include <wx/gdicmn.h>
#include <wx/scrolwin.h>
#include <wx/font.h>
#include <wx/colour.h>
#include <wx/settings.h>
#include <wx/string.h>
#include <wx/panel.h>

#include "rocs/public/list.h"
#include "rocs/public/map.h"
#include "rocs/public/node.h"

//// end generated include

/** Implementing WidgetsPanel */
class WidgetsPanel : public wxScrolledWindow
{
  iOList m_Widgets;
  iOMap m_WidgetsMap;
  int m_WidgetWidth;

	protected:
		// Handlers for WidgetsPanel events.
		void OnPanelSize( wxSizeEvent& event );
	public:
		/** Constructor */
		WidgetsPanel( wxWindow* parent, wxWindowID id = wxID_ANY,
		    const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize, long style = wxSUNKEN_BORDER|wxHSCROLL|wxVSCROLL );
    ~WidgetsPanel();
		void initView(iOList locolist);
    void updateLoco(iONode node);
    void updateLocoImg(iONode node);
    wxGridSizer* m_GridSizer;
};



#endif // __widgetspanel__
