/*
 Rocrail - Model Railroad Software
 Copyright (c) 2002-2015 Robert Jan Versluis, Rocrail.net
 All rights reserved.
*/

#ifndef __zoomdlg__
#define __zoomdlg__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "zoomdlggen.h"

//// end generated include

/** Implementing MyFrame1 */
class ZoomDlg : public ZoomDlgGen
{
	protected:
		// Handlers for MyFrame1 events.
		void onCancel( wxCommandEvent& event );
		void onOK( wxCommandEvent& event );
    void onZoomSelect( wxCommandEvent& event );
    void onZoomEnter( wxCommandEvent& event );
    void onZoomThumb( wxScrollEvent& event );
    void onZoomRelease( wxScrollEvent& event );
    void onHelp( wxCommandEvent& event );
	public:
		/** Constructor */
		ZoomDlg( wxWindow* parent, int percent );
	//// end generated class members
		int GetValue();
	
};

#endif // __zoomdlg__
